// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/handlers/get/url.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/avGenie/url-shortener/internal/app/entity"
	models "github.com/avGenie/url-shortener/internal/app/models"
	gomock "github.com/golang/mock/gomock"
)

// MockURLGetter is a mock of URLGetter interface.
type MockURLGetter struct {
	ctrl     *gomock.Controller
	recorder *MockURLGetterMockRecorder
}

// MockURLGetterMockRecorder is the mock recorder for MockURLGetter.
type MockURLGetterMockRecorder struct {
	mock *MockURLGetter
}

// NewMockURLGetter creates a new mock instance.
func NewMockURLGetter(ctrl *gomock.Controller) *MockURLGetter {
	mock := &MockURLGetter{ctrl: ctrl}
	mock.recorder = &MockURLGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLGetter) EXPECT() *MockURLGetterMockRecorder {
	return m.recorder
}

// GetURL mocks base method.
func (m *MockURLGetter) GetURL(ctx context.Context, userID entity.UserID, key entity.URL) (*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, userID, key)
	ret0, _ := ret[0].(*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockURLGetterMockRecorder) GetURL(ctx, userID, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockURLGetter)(nil).GetURL), ctx, userID, key)
}

// MockAllURLGetter is a mock of AllURLGetter interface.
type MockAllURLGetter struct {
	ctrl     *gomock.Controller
	recorder *MockAllURLGetterMockRecorder
}

// MockAllURLGetterMockRecorder is the mock recorder for MockAllURLGetter.
type MockAllURLGetterMockRecorder struct {
	mock *MockAllURLGetter
}

// NewMockAllURLGetter creates a new mock instance.
func NewMockAllURLGetter(ctrl *gomock.Controller) *MockAllURLGetter {
	mock := &MockAllURLGetter{ctrl: ctrl}
	mock.recorder = &MockAllURLGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllURLGetter) EXPECT() *MockAllURLGetterMockRecorder {
	return m.recorder
}

// GetAllURLByUserID mocks base method.
func (m *MockAllURLGetter) GetAllURLByUserID(ctx context.Context, userID entity.UserID) (models.AllUrlsBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllURLByUserID", ctx, userID)
	ret0, _ := ret[0].(models.AllUrlsBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllURLByUserID indicates an expected call of GetAllURLByUserID.
func (mr *MockAllURLGetterMockRecorder) GetAllURLByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllURLByUserID", reflect.TypeOf((*MockAllURLGetter)(nil).GetAllURLByUserID), ctx, userID)
}
