// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/storage/api/model/storage.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/avGenie/url-shortener/internal/app/entity"
	models "github.com/avGenie/url-shortener/internal/app/models"
	model "github.com/avGenie/url-shortener/internal/app/storage/api/model"
	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStorage) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorage)(nil).Close))
}

// DeleteBatchURL mocks base method.
func (m *MockStorage) DeleteBatchURL(ctx context.Context, urls entity.DeletedURLBatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatchURL", ctx, urls)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatchURL indicates an expected call of DeleteBatchURL.
func (mr *MockStorageMockRecorder) DeleteBatchURL(ctx, urls interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatchURL", reflect.TypeOf((*MockStorage)(nil).DeleteBatchURL), ctx, urls)
}

// GetAllURLByUserID mocks base method.
func (m *MockStorage) GetAllURLByUserID(ctx context.Context, userID entity.UserID) (models.AllUrlsBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllURLByUserID", ctx, userID)
	ret0, _ := ret[0].(models.AllUrlsBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllURLByUserID indicates an expected call of GetAllURLByUserID.
func (mr *MockStorageMockRecorder) GetAllURLByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllURLByUserID", reflect.TypeOf((*MockStorage)(nil).GetAllURLByUserID), ctx, userID)
}

// GetURL mocks base method.
func (m *MockStorage) GetURL(ctx context.Context, userID entity.UserID, key entity.URL) (*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, userID, key)
	ret0, _ := ret[0].(*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockStorageMockRecorder) GetURL(ctx, userID, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockStorage)(nil).GetURL), ctx, userID, key)
}

// PingServer mocks base method.
func (m *MockStorage) PingServer(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingServer", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingServer indicates an expected call of PingServer.
func (mr *MockStorageMockRecorder) PingServer(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingServer", reflect.TypeOf((*MockStorage)(nil).PingServer), ctx)
}

// SaveBatchURL mocks base method.
func (m *MockStorage) SaveBatchURL(ctx context.Context, userID entity.UserID, batch model.Batch) (model.Batch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatchURL", ctx, userID, batch)
	ret0, _ := ret[0].(model.Batch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBatchURL indicates an expected call of SaveBatchURL.
func (mr *MockStorageMockRecorder) SaveBatchURL(ctx, userID, batch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatchURL", reflect.TypeOf((*MockStorage)(nil).SaveBatchURL), ctx, userID, batch)
}

// SaveURL mocks base method.
func (m *MockStorage) SaveURL(ctx context.Context, userID entity.UserID, key, value entity.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveURL", ctx, userID, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveURL indicates an expected call of SaveURL.
func (mr *MockStorageMockRecorder) SaveURL(ctx, userID, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveURL", reflect.TypeOf((*MockStorage)(nil).SaveURL), ctx, userID, key, value)
}
